(function(){
const MODEL='https://cdn.3dassets.dev/assets/26695/v1/model.glb';
const VIEWER='https://ajax.googleapis.com/ajax/libs/model-viewer/4.3.1/model-viewer.min.js';
let ready=null,busy=false,overlay=null;
function load(){if(customElements.get('model-viewer'))return Promise.resolve();if(ready)return ready;ready=new Promise(function(ok,no){var s=document.createElement('script');s.type='module';s.src=VIEWER;s.onload=function(){customElements.whenDefined('model-viewer').then(ok)};s.onerror=no;document.head.appendChild(s)});return ready}
function css(){if(document.getElementById('ragwan3dcss'))return;var s=document.createElement('style');s.id='ragwan3dcss';s.textContent='.ragwan3d{position:fixed;inset:0;z-index:99999;background:radial-gradient(circle,rgba(20,91,70,.45),rgba(2,13,11,.94) 70%);display:flex;align-items:center;justify-content:center;opacity:0;transition:opacity .35s}.ragwan3d.show{opacity:1}.ragwan3dbox{position:relative;width:min(760px,94vw);height:min(820px,90vh);border-radius:28px;overflow:hidden;background:linear-gradient(145deg,#123c31,#041914);box-shadow:0 35px 100px #0009,0 0 55px #f2cc5840;transform:scale(.88) translateY(28px);transition:transform 1.15s cubic-bezier(.16,.82,.2,1)}.ragwan3d.show .ragwan3dbox{transform:scale(1) translateY(0)}.ragwan3dtop{position:absolute;top:0;left:0;right:0;z-index:2;padding:14px 18px;display:flex;justify-content:space-between;align-items:center;direction:rtl;color:#fff;font-weight:900}.ragwan3dnum{display:inline-grid;place-items:center;width:38px;height:38px;border-radius:50%;margin-left:8px;background:linear-gradient(145deg,#f7df88,#b8861b);color:#2c2411}.ragwan3dclose{width:42px;height:42px;border:1px solid #ffffff44;border-radius:50%;background:#ffffff18;color:#fff;font-size:24px}.ragwan3dviewer{position:absolute;inset:45px 10px 65px;width:calc(100% - 20px);height:calc(100% - 110px);background:transparent;--poster-color:transparent;--progress-bar-color:#f2cc58}.ragwan3dbottom{position:absolute;bottom:0;left:0;right:0;z-index:2;text-align:center;padding:10px 15px 16px;direction:rtl}.ragwan3dstatus{display:inline-block;padding:8px 15px;border-radius:999px;background:#ffffff12;border:1px solid #ffffff20;color:#eaf7f2;font-size:12px}.ragwan3denter{display:none;margin-top:8px;background:#16a66a!important;color:#fff!important;border:0!important}.ragwan3d.ready .ragwan3denter{display:inline-block}@media(max-width:620px){.ragwan3d{padding:7px}.ragwan3dbox{width:97vw;height:88vh;border-radius:23px}}';document.head.appendChild(s)}
function step(d){var m=String(d.id||'').match(/ragwanDoor(\d+)/);return m?Number(m[1]):1}
function open3d(d){if(busy)return;busy=true;css();var n=step(d),title=(d.querySelector('.ragwan-door-label')||{}).textContent||'الخطوة';overlay=document.createElement('div');overlay.className='ragwan3d';overlay.innerHTML='<div class="ragwan3dbox"><div class="ragwan3dtop"><div><span class="ragwan3dnum">'+n+'</span>'+title+'</div><button class="ragwan3dclose" type="button">×</button></div><model-viewer class="ragwan3dviewer" src="'+MODEL+'" camera-orbit="0deg 76deg 5.2m" camera-target="0m 1.3m 0m" field-of-view="28deg" interaction-prompt="none" disable-pan disable-tap shadow-intensity="1.1" exposure="1.05" tone-mapping="aces" environment-image="neutral" loading="eager"></model-viewer><div class="ragwan3dbottom"><div class="ragwan3dstatus">جارٍ تحميل الباب...</div><button class="ragwan3denter" type="button">الدخول إلى الخطوة ←</button></div></div>';document.body.appendChild(overlay);document.body.style.overflow='hidden';requestAnimationFrame(function(){overlay.classList.add('show')});
var v=overlay.querySelector('model-viewer'),st=overlay.querySelector('.ragwan3dstatus'),done=false,timer;
function finish(){if(done)return;done=true;if(timer)clearTimeout(timer);var fn=window.ragwanOpenDoor;if(fn){try{fn(n)}catch(e){console.error(e)}}document.body.style.overflow='';overlay.classList.remove('show');setTimeout(function(){overlay.remove();overlay=null;busy=false},360)}
overlay.querySelector('.ragwan3dclose').onclick=finish;overlay.querySelector('.ragwan3denter').onclick=finish;overlay.onclick=function(e){if(e.target===overlay)finish()};
load().then(function(){st.textContent='جارٍ تحميل الباب الواقعي...';v.addEventListener('load',function(){var a=v.availableAnimations||[],name=a.find(function(x){return x.toLowerCase()==='open'})||a.find(function(x){return x.toLowerCase().indexOf('open')>=0});if(!name){st.textContent='تم تحميل الباب';overlay.classList.add('ready');timer=setTimeout(finish,1200);return}v.animationName=name;v.currentTime=0;v.timeScale=.82;st.textContent='🚪 اقترب من الباب...';var start=performance.now(),fromR=5.2,toR=2.45,travel=3200;function approach(now){var p=Math.min(1,(now-start)/travel),e=1-Math.pow(1-p,3);try{var o=v.getCameraOrbit();o.radius=fromR+(toR-fromR)*e;v.cameraOrbit=o}catch(x){}if(p<1)requestAnimationFrame(approach);else{st.textContent='✨ تم فتح الباب';overlay.classList.add('ready');timer=setTimeout(finish,650)}}requestAnimationFrame(approach);setTimeout(function(){try{v.play({repetitions:1})}catch(x){}},650);},{once:true});v.addEventListener('finished',function(){},{once:true});v.addEventListener('error',function(){st.textContent='تعذر تحميل النموذج';timer=setTimeout(finish,700)},{once:true})}).catch(function(){st.textContent='تعذر تشغيل العرض ثلاثي الأبعاد';timer=setTimeout(finish,700)})}
window.ragwanDoor3DOpen=open3d;
document.addEventListener('click',function(e){var d=e.target.closest&&e.target.closest('.ragwan-door');if(!d||d.disabled||busy)return;var fn=window.ragwanOpenDoor;if(!fn)return;e.preventDefault();e.stopPropagation();open3d(d)},true);
})();